config/routes.rb
Rails.application.routes.draw do

root 'pages#home'
get 'about', to: 'pages#about'

get 'signup', to: 'users#new'

get 'login', to: 'sessions#new'

post 'login', to: 'sessions#create'

delete 'logout', to: 'sessions#destroy'

resources :users, except: [:new]

resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	validates :title, presence: true, length: {minimum: 3, maximum: 30}
	validates :description, presence: true, length: {minimum: 10, maximum: 300}
	validates :user_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord

	has_many :articles, dependent: :destroy
	before_save {self.email = email.downcase}
	validates :username, presence: true,
			   uniqueness: {case_sensitive: false}, 
			   length: {minimum: 3, maximum: 15}

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :email, presence: true, 
			   length: {maximum: 105},
			   uniqueness: {case_sensitive: false},
			   format: {with: VALID_EMAIL_REGEX}


	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
   helper_method :current_user, :logged_in?

def current_user

@current_user ||= User.find(session[:user_id]) if session[:user_id]

end

def logged_in?

!!current_user

end

def require_user

if !logged_in?

flash[:danger] = "You must be logged in to perform that action"

redirect_to root_path

end

end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_action :set_article, only: [:edit, :update, :show, :destroy]
	before_action :require_user, except: [:index, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]

	def index

		@articles = Article.paginate(page: params[:page], per_page: 10)

	end

	def new
		@article = Article.new
	end

	def create
		
		@article = Article.new(article_params)
		@article.user = current_user
		
		if @article.save
		flash[:success] = "Article was seccesfuly created"
		redirect_to article_path(@article )
		else
		render 'new'
		end
	end

	def edit
		

	end

	def update
		

		if @article.update(article_params)
		flash[:success] = "Article was seccesfuly updated"
		redirect_to article_path(@article )
		else
		render 'edit'
		end

		
	end

	def show
		

	end

	def destroy	

		@article.destroy
		flash[:deleted] = "Article was succesfully deleted"
		redirect_to articles_path
	end



	private

	def set_article
		@article= Article.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title, :description, :current_user)

	end

	def require_same_user
		if current_user != @article.user || !current_user.admin?
			flash[:deleted] = "You can only edit and delite your own article"
			redirect_to root_path
		end

	end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home

	end

	def about

	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new

	end


	def create

		 user = User.find_by(email: params[:session][:email].downcase)
	if user && user.authenticate(params[:session][:password])

		session[:user_id] = user.id

		flash[:success] = "You have successfully logged in"

		redirect_to user_path(user)

	else

		flash.now[:deleted] = "There was something wrong with your login information"

		render 'new'

	end

	end

	def destroy
		session[:user_id] = nil
		flash[:success] = "You have loged out"
		redirect_to root_path
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :set_user, only: [:edit, :update, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]
	before_action :require_admin , only: [:destroy]

	def index
		
		@users = User.paginate(page: params[:page], per_page: 5) 

	end

	def new

		@user = User.new

	end

	def create

		 @user = User.new(user_params)

		if @user.save
		session[:user_id] =@user.id
		flash[:success] = "Welcome to Alpha Blog #{@user.username}"
		redirect_to user_path(@user)
		else
		render 'new'
		end

	end

	def edit

	end

	def update


		if @user.update(user_params)
			flash[:success] = "Your account was updated"
			redirect_to articles_path
		else
			render 'edit'
		end

	end

	def show
		@user_articles =  @user.articles.paginate(page: params[:page], per_page: 5)
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		flash[:deleted] = "User and all users articles delited"
		redirect_to users_path
	end

	private
	def user_params

		params.require(:user).permit(:username, :email, :password)
		
	end

	def set_user
		@user = User.find(params[:id])

	end


	def require_same_user

		if current_user != @user && !current_user.admin?
			flash[:deleted] = "You can only edit and delite your own account"
			redirect_to root_path
		end

	end

	def require_admin
		if logged_in? && !current_user.admin?
			flash[:deleted] = "Only admin can delete accounts"
			redirect_to root_path
		end
	end


end

app/helpers/application_helper.rb
module ApplicationHelper

	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, class: "img-circle")
	end
end

app/views/articles/_article.html.erb
<% obj.each do |article|%>
<% id = article.id %>

<p>
<ul class="allarticles">

<li style="padding-top: 5px;font-size: 20px "><%= link_to "#{article.title}", article_path(article)%> </li><br>
<li style="font-size: 10px"><%=truncate(article.description, length: 100)%><br><br>
<%if logged_in? && (current_user == article.user || current_user.admin?)%>
	<%=link_to "Edit", edit_article_path(article), class: "editBtn1"%> | <%= link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are you sure="}, class: "editBtn3"%> <%end%>
	<h5 style="font-size: 11px;float: right;position: relative; margin-right:3px">Created by: <%=link_to "#{article.user.username}", user_path(article.user) if article.user %>, <%=time_ago_in_words(article.created_at)%> ago, last update: <%= time_ago_in_words(article.updated_at)%></h5><br><br>

</ul>
</p>




<%end%>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article%>

<%= form_for(@article, :html => {class: "formular", role: "form"}) do |f| %>


<% f.label :title %>
<%= f.text_field :title, class: "txttitle", placeholder: "Article title", autofocus: true%>


<% f.label :description %>
<%= f.text_area :description, rows: 10, class: "txtDescription" %>	

<%= f.submit%> 


<%= link_to "Back to article listing", articles_path%> 


<%end%>

app/views/articles/edit.html.erb
<h1> Edit your article</h1>


<%= render "form"%>

app/views/articles/index.html.erb
<h1 style="text-align: center; font-weight: bold"> All articles </h1>
<div align="center" ">
<%= will_paginate%>
</div>
<%= render 'article', obj: @articles%>

<div align="center" ">
<%= will_paginate%>
</div>

app/views/articles/new.html.erb
<br><br>
<h1 style="text-align: center; font-weight: bold"> Create a new articles</h1>
<%= render 'form' %>

  

app/views/articles/show.html.erb
<div class="showArticle">
	<div class="title">
	<h3><%= @article.title%> </h3> <br>
	</div>
<div class="description">
	<h3> Description:<br><br><br></h3>
	<%= simple_format(@article.description)%>
	<% if logged_in? && (current_user == @article.user || current_user.admin?)%>
	<%= link_to "Edit this article", edit_article_path(@article), class: "editBtn1"%> |
	<%= link_to "Back to article listing", articles_path, class: "editBtn2"%> | 
	<%= link_to "Delete article", article_path(@article), method: :delete, data: {confirm: "Do you want to delete article?"}, class: "editBtn3" %><div style="float: right; padding-right: 10px; padding-bottom: -10px;"><%end%>
	Created by: <%= link_to "#{@article.user.username}", user_path(@article.user)%></div>

</div>
</div>

app/views/layouts/_footer.html.erb
<div style="position: relative; bottom: 0; right: 0; left: 0; background-color: gray; width: 100%; ">
Copyright &copy; 
Designed by Haris Cavkic
<div>

app/views/layouts/_messages.html.erb
  <% flash.each do |name, msg|%>
  <div id='<%="#{name}"%>'>
  		

  		
  		<h4><%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %></h4>
  		
  	


  <%end%>
  </div>
 

app/views/layouts/_navigation.html.erb
<nav class="navBar">
            <div class="logo"><%= link_to "ALPHA BLOG", root_path, class: "logoRB"%></div>
         

        <% if logged_in? %>
          <ul class="linkovi">
            <li class="ponudiPrijevoz"><%= link_to "New article", new_article_path, class: "logoRB"%></li>
            <li class="RegLog"><%= "Admin" if current_user.admin?%> Profile 
	            <ul class="dropdown_ul">
		            <li><%=link_to"Edit profile", edit_user_path(current_user),  class: "RegLog2"%></li>
		            <li><%=link_to"View profile", user_path(current_user),  class: "RegLog2"%></li>
		            <li><%=link_to"Logout", logout_path, method: :delete,  class: "RegLog2"%></li>
	            </ul>
	        </li>
          
          </ul>

        <% else %>

          <ul class="linkovi">
            <li class="RegLog"><%=link_to"Sign up", signup_path, class: "RegLog2"%></li>
            <li class="RegLog"><%=link_to"Log in", login_path, class: "RegLog2"%></li>
          </ul>

        <%end%>
</nav>

 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>AlphaBlog</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <body>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <%= render "layouts/navigation"%><br> <br>
      <%= render "layouts/messages"%>

    <div class="svaki">
      
    
      <%= yield %>

    </div>
    
    
    
<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script>
    setTimeout("$('.error_msgs').fadeOut('slow')", 6000)
    setTimeout("$('.success_msgs').fadeOut('slow')", 3000)
    </script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/nav2.html.erb
<nav class="navBar">
            <div class="logo"><%= link_to "ALPHA BLOG", root_path, class: "logoRB"%></div>
         
          <ul class="linkovi">
        <% if logged_in?%>
            <li class="ponudiPrijevoz"><%= link_to "New article", new_article_path, class: "logoRB"%></li>
            <li class="drowpdown_profil"><%=link_to"Log out", logout_path, method: :delete%>
              <ul>
                <li><%=link_to"Log out", logout_path, method: :delete, class: "RegLog2"%></li>
                <li><%=link_to"Log out", logout_path, method: :delete%><</li>
              </ul>
            </li>
        <%else%>
            <li class="RegLog"><%=link_to"Sign up", signup_path, class: "RegLog2"%></li>
            <li class="RegLog"><%=link_to"Login", login_path, class: "RegLog2"%></li></li>
         <%end%>
          </ul>
</nav>



<nav>
            <p><%= link_to "ALPHA BLOG", root_path, class: "logoRB"%><p>
         
         <% if logged_in?%>
          <ul>
            <li><a><%= link_to "New article", new_article_path%></a></li>
            <li><a href="#">Profile</a>
              <ul>
                <li><%=link_to"Log out", logout_path, class: "reglog", method: :delete%></li>
                <li><%=link_to"Log out", logout_path, class: "reglog", method: :delete%></li>
              </ul>
            </li>
          </ul>
        <%else%>

          <ul class="linkovi">
            <li class="RegLog"><%=link_to"Sign up", signup_path, class: "RegLog2"%></li>
            <li class="RegLog"><%=link_to"Login", login_path, class: "RegLog2"%></li></li>
          </ul>
         <%end%>
          </ul>
</nav>

app/views/pages/about.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    
 <%= link_to 'Home', root_path %>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>
 

app/views/pages/home.html.erb
<div class="sajnap">

 	<%= link_to "ALL ARTICLES", articles_path, class: "linkoviHome"%>      <%= link_to "NEW ARTICLE", new_article_path, class: "linkoviHome"%>


</div>
 	

  

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="poruka">
	 <%= pluralize(obj.errors.count, "error")%> found:
<ul>
	<% obj.errors.full_messages.each do |msg|%>
	<li><%= msg %></li>
	<%end%>
</ul>
<%end%>
</div>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user%>


<%= form_for(@user, :html => {class: "formular", role: "form"}) do |f| %>

<h2 style="font-weight: bold; text-align: center; "> <%= @user.new_record? ? "Sign up for Alpha Blog" : "Edit your account"%> </h2>

<% f.label :username %>
<%= f.text_field :username, class: "txttitle", placeholder: "Enter username", autofocus: true%>


<% f.label :email %>
<%= f.email_field :email, placeholder:"Enter email", class: "txttitle" %>

<% f.label :password %>
<%= f.password_field :password, placeholder: "Enter password", class: "txttitle" %>


<%= f.submit (@user.new_record? ? "Sign up" : "Update")%> 


<%= link_to "Back to article listing", articles_path%> 


<%end%>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<h1 style="font-weight: bold; text-align: center"> All Alpha bloggers </h1>
<div align="center" ">
<%= will_paginate%>
</div>
<% @users.each do |user| %>


<ul class="allusers">

<li style="padding-top: 5px;font-size: 20px "><%= link_to "#{user.username}", user_path(user)%> </li><br>
<li><%= link_to gravatar_for(user), user_path(user)%></li>
<li style="font-size: 10px; padding-top: 10px;"><%= pluralize(user.articles.count, "article") if user.articles%></li>
<% if logged_in? && current_user.admin?%>
<li><%= link_to "Delete user", user_path(user), method: :delete, data: {confirm: "Do you want to delete user?"}, class: "editBtn3" %></li>
<%end%>
</ul>





<%end%>
<div align="center" ">
<%= will_paginate%>
</div>

app/views/users/new.html.erb
<%= render 'shared/errors', obj: @user%>


<%= form_for(@user, :html => {class: "formular", role: "form"}) do |f| %>

<h2 style="font-weight: bold; text-align: center; "> Sign up for Alpha Blog </h2>

<% f.label :username %>
<%= f.text_field :username, class: "txttitle", placeholder: "Enter username", autofocus: true%>


<% f.label :email %>
<%= f.email_field :email, placeholder:"Enter email", class: "txttitle" %>

<% f.label :password %>
<%= f.password_field :password, placeholder: "Enter password", class: "txttitle" %>


<%= f.submit "Sign up"%> 


<%= link_to "Back to article listing", articles_path%> 


<%end%>

app/views/users/show.html.erb
<h1>Welcom to <%= @user.username%>'s page</h1><br>


<%= gravatar_for @user %> <br><br>
<% u_id = @user.id%>

<h4><%=@user.username%>'s articles:</h4><br>

<% if @user.articles.count>5%>
<div align="center" ">
<%= will_paginate @user_articles%>
</div>
<%end%>
<%= render 'articles/article', obj: @user_articles%>